/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sp4_hagelauer_chauvet;

/**
 *
 * @author ylanc
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau_infoJoueur = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JetonsRestantsJ1 = new javax.swing.JTextField();
        couleur_j1 = new javax.swing.JTextField();
        nom_j1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JetonsRestantsJ2 = new javax.swing.JTextField();
        couleur_j2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nom_j2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Panneau_creationPartie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur1 = new javax.swing.JTextField();
        nom_joueur2 = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        Panneau_infoPartie = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Panneau_grille = new javax.swing.JPanel();
        col2 = new javax.swing.JButton();
        col3 = new javax.swing.JButton();
        col4 = new javax.swing.JButton();
        col5 = new javax.swing.JButton();
        col6 = new javax.swing.JButton();
        col7 = new javax.swing.JButton();
        col1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panneau_infoJoueur.setBackground(new java.awt.Color(204, 0, 204));
        Panneau_infoJoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Infos Joueur:");
        Panneau_infoJoueur.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 88, 26));

        jLabel4.setText("Joueur 1:");
        Panneau_infoJoueur.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 46, 65, -1));

        jLabel5.setText("Couleur:");
        Panneau_infoJoueur.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 65, -1));

        jLabel9.setText("Jetons Restants:");
        Panneau_infoJoueur.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 98, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Panneau_infoJoueur.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 250, 10));

        JetonsRestantsJ1.setText("jTextField1");
        Panneau_infoJoueur.add(JetonsRestantsJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 95, 60, -1));

        couleur_j1.setText("jTextField1");
        Panneau_infoJoueur.add(couleur_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 69, 60, -1));

        nom_j1.setText("jTextField1");
        Panneau_infoJoueur.add(nom_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 43, 60, -1));

        jLabel10.setText("Jetons Restants:");
        Panneau_infoJoueur.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, 98, -1));

        JetonsRestantsJ2.setText("jTextField1");
        Panneau_infoJoueur.add(JetonsRestantsJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 201, 60, -1));

        couleur_j2.setText("jTextField1");
        Panneau_infoJoueur.add(couleur_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 175, 60, -1));

        jLabel11.setText("Joueur 2:");
        Panneau_infoJoueur.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 152, 65, -1));

        nom_j2.setText("jTextField1");
        Panneau_infoJoueur.add(nom_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 149, -1, -1));

        jLabel12.setText("Couleur:");
        Panneau_infoJoueur.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 65, -1));

        getContentPane().add(Panneau_infoJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 376, 250, 250));

        Panneau_creationPartie.setBackground(new java.awt.Color(204, 0, 204));
        Panneau_creationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 2:");
        Panneau_creationPartie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("Nom Joueur 1:");
        Panneau_creationPartie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        nom_joueur1.setText("jTextField1");
        Panneau_creationPartie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        nom_joueur2.setText("jTextField1");
        Panneau_creationPartie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        start.setText("Démarrer Partie !");
        Panneau_creationPartie.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        getContentPane().add(Panneau_creationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 50, 250, 120));

        Panneau_infoPartie.setBackground(new java.awt.Color(204, 0, 204));
        Panneau_infoPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Infos Partie:");
        Panneau_infoPartie.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, -1));
        Panneau_infoPartie.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jTextField1.setText("JoueurCourant");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Panneau_infoPartie.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));
        Panneau_infoPartie.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 250, 10));

        getContentPane().add(Panneau_infoPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 170, 250, 210));

        Panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        Panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(Panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 672, 576));

        col2.setText("2");
        getContentPane().add(col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 20, -1, -1));

        col3.setText("3");
        getContentPane().add(col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 20, -1, -1));

        col4.setText("4");
        col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col4ActionPerformed(evt);
            }
        });
        getContentPane().add(col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 20, -1, -1));

        col5.setText("5");
        col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col5ActionPerformed(evt);
            }
        });
        getContentPane().add(col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 20, -1, -1));

        col6.setText("6");
        getContentPane().add(col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        col7.setText("7");
        getContentPane().add(col7, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 20, -1, -1));

        col1.setText("1");
        col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ActionPerformed(evt);
            }
        });
        getContentPane().add(col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        setBounds(0, 0, 1044, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_col1ActionPerformed

    private void col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_col4ActionPerformed

    private void col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_col5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JetonsRestantsJ1;
    private javax.swing.JTextField JetonsRestantsJ2;
    private javax.swing.JPanel Panneau_creationPartie;
    private javax.swing.JPanel Panneau_grille;
    private javax.swing.JPanel Panneau_infoJoueur;
    private javax.swing.JPanel Panneau_infoPartie;
    private javax.swing.JButton col1;
    private javax.swing.JButton col2;
    private javax.swing.JButton col3;
    private javax.swing.JButton col4;
    private javax.swing.JButton col5;
    private javax.swing.JButton col6;
    private javax.swing.JButton col7;
    private javax.swing.JTextField couleur_j1;
    private javax.swing.JTextField couleur_j2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nom_j1;
    private javax.swing.JTextField nom_j2;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
