/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sp4_hagelauer_chauvet;

/**
 *
 * @author ylanc
 */
public class fenetreDeJeu extends javax.swing.JFrame {
    
   Joueur ListeJoueurs[]= new Joueur[2];
   Joueur JoueurCourant;
   Grille grilleJeu= new Grille();
    public fenetreDeJeu() {
        initComponents();
        Panneau_infoJoueur.setVisible(false);
        Panneau_infoPartie.setVisible(false);
        for (int i=5; i>=0; i--){
            for (int j=0; j<7; j++){
                CelluleGraphique cellGraph= new CelluleGraphique(grilleJeu.cellule[i][j]);
                Panneau_grille.add(cellGraph);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau_infoJoueur = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JetonsRestantsJ1 = new javax.swing.JTextField();
        couleur_j1 = new javax.swing.JTextField();
        nom_j1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JetonsRestantsJ2 = new javax.swing.JTextField();
        couleur_j2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nom_j2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Panneau_creationPartie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur2 = new javax.swing.JTextField();
        nom_joueur1 = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        Panneau_infoPartie = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        joueurCourant = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Message = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        Panneau_grille = new javax.swing.JPanel();
        col1 = new javax.swing.JButton();
        col2 = new javax.swing.JButton();
        col3 = new javax.swing.JButton();
        col4 = new javax.swing.JButton();
        col5 = new javax.swing.JButton();
        col6 = new javax.swing.JButton();
        col7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panneau_infoJoueur.setBackground(new java.awt.Color(204, 0, 204));
        Panneau_infoJoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Infos Joueur:");
        Panneau_infoJoueur.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 6, 88, 26));

        jLabel4.setText("Joueur 1:");
        Panneau_infoJoueur.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 46, 65, -1));

        jLabel5.setText("Couleur:");
        Panneau_infoJoueur.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 65, -1));

        jLabel9.setText("Jetons Restants:");
        Panneau_infoJoueur.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 98, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Panneau_infoJoueur.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 250, 10));
        Panneau_infoJoueur.add(JetonsRestantsJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 95, 60, -1));
        Panneau_infoJoueur.add(couleur_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 69, 60, -1));

        nom_j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_j1ActionPerformed(evt);
            }
        });
        Panneau_infoJoueur.add(nom_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 43, 60, -1));

        jLabel10.setText("Jetons Restants:");
        Panneau_infoJoueur.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, 98, -1));

        JetonsRestantsJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JetonsRestantsJ2ActionPerformed(evt);
            }
        });
        Panneau_infoJoueur.add(JetonsRestantsJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 201, 60, -1));
        Panneau_infoJoueur.add(couleur_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 175, 60, -1));

        jLabel11.setText("Joueur 2:");
        Panneau_infoJoueur.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 152, 65, -1));
        Panneau_infoJoueur.add(nom_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 149, 60, -1));

        jLabel12.setText("Couleur:");
        Panneau_infoJoueur.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 65, -1));

        getContentPane().add(Panneau_infoJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 376, 250, 250));

        Panneau_creationPartie.setBackground(new java.awt.Color(204, 0, 204));
        Panneau_creationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur 2:");
        Panneau_creationPartie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("Nom Joueur 1:");
        Panneau_creationPartie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        Panneau_creationPartie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, -1));

        nom_joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur1ActionPerformed(evt);
            }
        });
        Panneau_creationPartie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 70, -1));

        start.setText("Démarrer Partie !");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        Panneau_creationPartie.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        getContentPane().add(Panneau_creationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 50, 250, 120));

        Panneau_infoPartie.setBackground(new java.awt.Color(204, 0, 204));
        Panneau_infoPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Infos Partie:");
        Panneau_infoPartie.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, -1));
        Panneau_infoPartie.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        joueurCourant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joueurCourantActionPerformed(evt);
            }
        });
        Panneau_infoPartie.add(joueurCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));
        Panneau_infoPartie.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 250, 10));

        message.setColumns(20);
        message.setRows(5);
        Message.setViewportView(message);

        Panneau_infoPartie.add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(Panneau_infoPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 170, 250, 210));

        Panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        Panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(Panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 672, 576));

        col1.setText("1");
        col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col1ActionPerformed(evt);
            }
        });
        getContentPane().add(col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        col2.setText("2");
        col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col2ActionPerformed(evt);
            }
        });
        getContentPane().add(col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 20, -1, -1));

        col3.setText("3");
        col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col3ActionPerformed(evt);
            }
        });
        getContentPane().add(col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 20, -1, -1));

        col4.setText("4");
        col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col4ActionPerformed(evt);
            }
        });
        getContentPane().add(col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 20, -1, -1));

        col5.setText("5");
        col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col5ActionPerformed(evt);
            }
        });
        getContentPane().add(col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 20, -1, -1));

        col6.setText("6");
        col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col6ActionPerformed(evt);
            }
        });
        getContentPane().add(col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        col7.setText("7");
        col7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col7ActionPerformed(evt);
            }
        });
        getContentPane().add(col7, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 20, -1, -1));

        setBounds(0, 0, 1044, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col1ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(1);
        if (grilleJeu.colonneRemplie(1)==true){
            col1.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col1ActionPerformed

    private void col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col4ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(4);
        if (grilleJeu.colonneRemplie(4)==true){
            col4.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col4ActionPerformed

    private void col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col5ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(5);
        if (grilleJeu.colonneRemplie(5)==true){
            col5.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col5ActionPerformed

    private void joueurCourantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joueurCourantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joueurCourantActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        Panneau_infoJoueur.setVisible(true);
        Panneau_infoPartie.setVisible(true);
        initialiserPartie();
        joueurCourant.setText(JoueurCourant.Nom);
        JetonsRestantsJ1.setText("21");
        JetonsRestantsJ2.setText("21");
        Panneau_grille.repaint();
        start.setEnabled(false);
    }//GEN-LAST:event_startActionPerformed

    private void nom_joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur1ActionPerformed

    private void nom_j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_j1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_j1ActionPerformed

    private void JetonsRestantsJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JetonsRestantsJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JetonsRestantsJ2ActionPerformed

    private void col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col2ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(2);
        if (grilleJeu.colonneRemplie(2)==true){
            col2.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col2ActionPerformed

    private void col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col3ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(3);
        if (grilleJeu.colonneRemplie(3)==true){
            col3.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col3ActionPerformed

    private void col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col6ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(6);
        if (grilleJeu.colonneRemplie(6)==true){
            col6.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col6ActionPerformed

    int tdj=1;//variable utilisé pour donner le nombre de jeton restant par joueur
    int tourdejeu=42;//variable tour de jeu
    public boolean jouerdansColonne(int indice_colonne){
       boolean resultatAction;
       Jeton jeton;
       int a;
       int j=0;//variable pour éviter la répétition d'égalité
       a= JoueurCourant.nombreJetonsRestant;
       jeton= JoueurCourant.ListeJetons[a-1];
       resultatAction=grilleJeu.ajouterJetonDansColonne(jeton,indice_colonne);
       boolean victj1= grilleJeu.etreGagnantePourJoueur(ListeJoueurs[0]);
       boolean victj2= grilleJeu.etreGagnantePourJoueur(ListeJoueurs[1]);
       
       if (victj1==true){
           col1.setEnabled(false);
           col2.setEnabled(false);
           col3.setEnabled(false);
           col4.setEnabled(false);
           col5.setEnabled(false);
           col6.setEnabled(false);
           col7.setEnabled(false);
           message.setText("Victoire de "+ListeJoueurs[0].Nom+" !!!");
       }
       if (victj2==true){
           col1.setEnabled(false);
           col2.setEnabled(false);
           col3.setEnabled(false);
           col4.setEnabled(false);
           col5.setEnabled(false);
           col6.setEnabled(false);
           col7.setEnabled(false);
           message.setText("Victoire de "+ListeJoueurs[1].Nom+" !!!");
       }
       if (grilleJeu.etreremplie()==true){
           col1.setEnabled(false);
           col2.setEnabled(false);
           col3.setEnabled(false);
           col4.setEnabled(false);
           col5.setEnabled(false);
           col6.setEnabled(false);
           col7.setEnabled(false);
           message.setText("égalité !!!");
           return true;
       }
       if (resultatAction==true){
           
           Panneau_grille.repaint();
           tourdejeu= tourdejeu-1;
           if ((tourdejeu)%2==0){
               tdj=(tourdejeu)/2;
               if (JoueurCourant==ListeJoueurs[0]){
                   String k= String.valueOf(tdj);
                   JetonsRestantsJ1.setText(k);
               }else{
                   String k= String.valueOf(tdj);
                   JetonsRestantsJ2.setText(k);
               }
           }else{
               tdj=(tourdejeu-1)/2;
               if (JoueurCourant==ListeJoueurs[0]){
                   String k= String.valueOf(tdj);
                   JetonsRestantsJ1.setText(k);
               }else{
                   String k= String.valueOf(tdj);
                   JetonsRestantsJ2.setText(k);
               }
           }
           if (tdj==0){
           col1.setEnabled(false);
           col2.setEnabled(false);
           col3.setEnabled(false);
           col4.setEnabled(false);
           col5.setEnabled(false);
           col6.setEnabled(false);
           col7.setEnabled(false);
           message.setText("égalité !!!");   
           }
          return true; 
       }
        return false;
    }
    public void joueurSuivant(){
        if (JoueurCourant== ListeJoueurs[0]){
            JoueurCourant= ListeJoueurs[1];
        }else{
            JoueurCourant= ListeJoueurs[0];
        }
        joueurCourant.setText(JoueurCourant.Nom);
    }
    private void col7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col7ActionPerformed
        // TODO add your handling code here:
        jouerdansColonne(7);
        if (grilleJeu.colonneRemplie(7)==true){
            col7.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_col7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }
    
    void attribuerCouleursAuxJoueurs(){ //Associe une couleur aux 2 joueurs stocké dans Couleurs
       double a= Math.random();//création d'une variable aléatoire entre 0 et 1
       
       if (a<0.5){
           ListeJoueurs[0].Couleur = "Rouge";
           ListeJoueurs[1].Couleur = "Jaune";
       }
       if (a>0.5){
           ListeJoueurs[1].Couleur = "Rouge";
           ListeJoueurs[0].Couleur = "Jaune";
       }
   }
    
     void initialiserPartie(){//on créé une grille et on associe les jetons aux joueurs
         
       String Joueur1= nom_joueur1.getText();
       Joueur J1 = new Joueur(Joueur1);
       String Joueur2= nom_joueur2.getText();
       Joueur J2 = new Joueur(Joueur2);
       
       ListeJoueurs[0]= J1;
       ListeJoueurs[1]= J2;
       
       attribuerCouleursAuxJoueurs();
       
       nom_j1.setText(Joueur1);
       nom_j2.setText(Joueur2);
       couleur_j1.setText(ListeJoueurs[0].Couleur);
       couleur_j2.setText(ListeJoueurs[1].Couleur);
       
       grilleJeu= new Grille();
       grilleJeu.vidergrille();
       
       if ("Rouge".equals(ListeJoueurs[0].Couleur)){
           JoueurCourant= ListeJoueurs[0];
       }else{
           JoueurCourant= ListeJoueurs[1];
       }
       
       String couleur= ListeJoueurs[0].Couleur;
       Jeton jeton= new Jeton(couleur);
       for (int i=0;i<21;i++){
           ListeJoueurs[0].ajouterJeton(jeton);
       }
       String couleur2= ListeJoueurs[1].Couleur;
       Jeton jeton2= new Jeton(couleur2);
       for (int i=0;i<21;i++){
           ListeJoueurs[1].ajouterJeton(jeton2);
       }
       int colonneAleatoire = (int)(Math.random()*7);
       int ligneAleatoire = (int)(Math.random()*6);
       int g=0;
       while(g<5){
           if (grilleJeu.cellule[ligneAleatoire][colonneAleatoire].presenceTrouNoir()==false){
               grilleJeu.placerTrouNoir(ligneAleatoire, colonneAleatoire);
               ligneAleatoire=(int)(Math.random()*6);
               colonneAleatoire=(int)(Math.random()*7);
               g=g+1;
           }else{
               ligneAleatoire=(int)(Math.random()*6);
               colonneAleatoire=(int)(Math.random()*7);
           }
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JetonsRestantsJ1;
    private javax.swing.JTextField JetonsRestantsJ2;
    private javax.swing.JScrollPane Message;
    private javax.swing.JPanel Panneau_creationPartie;
    private javax.swing.JPanel Panneau_grille;
    private javax.swing.JPanel Panneau_infoJoueur;
    private javax.swing.JPanel Panneau_infoPartie;
    private javax.swing.JButton col1;
    private javax.swing.JButton col2;
    private javax.swing.JButton col3;
    private javax.swing.JButton col4;
    private javax.swing.JButton col5;
    private javax.swing.JButton col6;
    private javax.swing.JButton col7;
    private javax.swing.JTextField couleur_j1;
    private javax.swing.JTextField couleur_j2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField joueurCourant;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField nom_j1;
    private javax.swing.JTextField nom_j2;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
